name: Add subtitle in video
on:
  workflow_dispatch:
    inputs:
      url:
        description: The URL to process
        required: true
      model:
        description: The model name to use (optional)
        required: false
        default: "base"
jobs:
  run-with-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install pipenv and ffmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install pipenv

      - name: Setup and run the script
        run: |
          pipenv install
          pipenv run python main.py ${{ github.event.inputs.url }} --model ${{ github.event.inputs.model }}
          
